import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  verification: {
    google: "teWyDbkkLKbIO8Rk7k0Q2H-nSE_0_MGJpzSmw8Kmjck",
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body
        className={`antialiased min-h-screen flex flex-col`}
      >
        <Header />
        <main className="px-2 flex flex-col flex-grow pb-2">
          {children}
        </main>
      </body>
    </html>
  );
}
